// The product manifest is the contract shared by the pipeline, the viewer and bosq.ae.
// It is generated by pipeline/run.mjs from models-src/<slug>/product.json + the model itself.

export type Locale = "en" | "ar";
export type LocalisedText = Partial<Record<Locale, string>> & { en: string };

/** Material roles — what a GLB material *is*, independent of its export name. */
export type MaterialRole = "upholstery" | "mesh" | "frame" | "base" | "hardware" | "plastic" | "wood" | "glass" | "other";

export interface MaterialOverride {
  color?: string; // hex
  roughness?: number;
  metalness?: number;
  /** For the mesh role: render as solid fabric instead of perforated mesh (e.g. Orca Echo Green). */
  solid?: boolean;
}

export interface Variant {
  sku: string;
  color: string; // matches bosq.ae attr_color
  label: string;
  swatch: string; // hex shown in the UI
  /** Overrides keyed by material *role* (or exact GLB material name). */
  materials: Record<string, MaterialOverride>;
}

export interface Hotspot {
  id: string;
  position: [number, number, number];
  title: LocalisedText;
  body?: LocalisedText;
}

export interface ProductManifest {
  slug: string;
  version: number;
  name: LocalisedText;
  description: Partial<Record<Locale, string>>;
  category: string;
  model: { high: string; low: string; usdz: string | null };
  poster: string;
  og: string | null;
  bounds: { w: number; d: number; h: number; center: [number, number, number] };
  dimensionsLabel: string | null;
  camera: { position: [number, number, number]; target: [number, number, number]; fov: number };
  /** GLB material name → role. */
  materials: Record<string, { role: MaterialRole }>;
  variants: Variant[];
  hotspots: Hotspot[];
  stats: {
    source: { triangles: number; sizeBytes: number };
    high: { triangles: number; sizeBytes: number; file: string };
    low: { triangles: number; sizeBytes: number; file: string };
  };
  productUrl: string | null;
  generatedAt: string;
}

export function t(text: LocalisedText | Partial<Record<Locale, string>> | undefined, locale: Locale): string {
  if (!text) return "";
  return text[locale] ?? text.en ?? "";
}
